#!/bin/bash
#$ -N VideoCaptioner
#$ -l gpu=1
#$ -l debian8
#$ -q default.q
#$ -e $HOME/code/logs/$JOB_NAME-$JOB_ID.err
#$ -o $HOME/code/logs/$JOB_NAME-$JOB_ID.out

module load cuda/8.0

python --version

cd $HOME/code/caption-guided-saliency

# python preprocessing.py --dataset MSR-VTT

python run_s2vt.py --dataset MSR-VTT --train

python run_s2vt.py --dataset MSR-VTT --test --checkpoint 99

# python visualization.py --dataset MSR-VTT --media_id video9461 --checkpoint 99 --sentence "A man is driving a car"

